model:
  model_path: "randomwalks/1M"
  tokenizer_path: "randomwalks/1M"
  model_type: "AcceleratePPOModel"
  num_layers_unfrozen: -1

train:
  seq_length: 10
  batch_size: 100
  epochs: 20
  total_steps: 1000

  lr_init: 4.0e-4
  lr_target: 4.0e-4
  opt_betas: [0.9, 0.95]
  opt_eps: 1.0e-8
  weight_decay: 1.0e-6

  checkpoint_interval: 10000
  eval_interval: 20

  pipeline: "PromptPipeline"
  orchestrator: "PPOOrchestrator"

method:
  name: 'ppoconfig'
  num_rollouts: 128
  chunk_size: 128
  ppo_epochs: 4
  init_kl_coef: 0.05
  target: 6
  horizon: 10000
  gamma: 1
  lam: 0.95
  cliprange: 0.2
  cliprange_value: 0.2
  vf_coef: 1.2
  scale_reward: False
  ref_mean: null
  ref_std: null
  cliprange_reward: 1
  gen_kwargs:
    max_length: 10
    min_length: 2
    top_k: 0.0
    top_p: 1.0
    do_sample: True
